apps/producto/urls.py
from django.urls import path
from . import views
from apps.producto.views import *

app_name = "producto_app"


urlpatterns = [
     path("producto/ajax", producto_ajax, name="producto_ajax"),
     path("producto/<pk>", views.ProductDetailView.as_view(), name='producto_detail'),
     path('productos', views.ProductosListView.as_view(), name='producto_all'),
     path('productos-categoria/<int:pk>', views.ProductosByCategoriaListView.as_view(), name='producto_categoria'),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', 
        admin.site.urls
    ),
    path('', 
        include(('apps.home.urls'), namespace='home'),
    ),
    path('', 
        include(('apps.categoria.urls'), namespace='categoria'),
    ),
    #path('', include('apps.carrusel.urls')),
    path('', include(('apps.producto.urls'), namespace='producto')),
    path('', include(('apps.marca.urls'), namespace='marca')),
    path('', include(('apps.login.urls'), namespace='login')),
    path('', include(('apps.busqueda.urls'), namespace='busqueda')),
    path('', include(('apps.carrusel.urls'), namespace='carrusel')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/producto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import model_to_dict
from apps.categoria.models import Categoria
from apps.marca.models import Marca

from distribuidora.settings.local import MEDIA_URL




class Producto(models.Model):
    nombre_producto = models.CharField(max_length=20, verbose_name="Nombre del producto")
    descripcion_producto = models.CharField(max_length=200, blank = True, null = True, verbose_name="Descripción")
    img_producto = models.ImageField(upload_to='productos_empresa/',verbose_name='Imagen', 
    null=True, blank=True,default='img_defecto.jpg')
    fecha_registro = models.DateField(auto_now_add=True,blank=True,null=True)
    precio = models.FloatField(default=0,blank = True, null = True, verbose_name="Precio")
    estado_producto = models.BooleanField(default = True, verbose_name="Estado")
    modelo = models.CharField(max_length=200,blank=True,null=True, verbose_name="Modelo")
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name="Categoría")
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, verbose_name="Marca",blank=True,null=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}".format(self.pk,self.nombre_producto)

    def toJSON(self):
        item = model_to_dict(self) #Convertimos todos los objetos en diccionarios
        item['img_producto'] = self.img_producto.url
        item['categoria'] = {'id': self.categoria.id, 'nombre': self.categoria.nombre_categoria}
        if self.marca == None:
            item['marca'] = {'id': 0, 'nombre': 'No registrado'}
        else:
            item['marca'] = {'id': self.marca.id, 'nombre': self.marca.nombre_marca}
        return item

apps/producto/views.py
import re
from django.shortcuts import render
from django.http import JsonResponse 
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required #Manejo de permisos

from apps.marca.models import Marca
from apps.producto.models import Producto
from apps.categoria.models import Categoria

#importacion para clases de
from django.views.generic import ListView, DetailView, TemplateView


# Create your views here.
@login_required	
def producto_ajax (request):
    if request.method == 'POST' and request.is_ajax():
        data = []
        try:
            action = request.POST['action']
            if action == 'buscardatos':
                for i in Producto.objects.all():
                    data.append(i.toJSON())
            elif action == 'crear':

                pro = Producto()
                pro.nombre_producto = request.POST['nombre_producto']
                pro.descripcion_producto = request.POST['descripcion']
                pro.categoria = Categoria.objects.get(pk=request.POST['id_categoria'])

                if int(request.POST['id_marca']) > 0:
                    pro.marca = Marca.objects.get(pk=request.POST['id_marca'])

                pro.usuario = User.objects.get(pk=request.user.id)
                pro.save()

                if request.FILES: 
                    imagen = request.FILES.get("imagen") 
                    imagen.name = str(pro.pk)+"_"+imagen.name
                    pro.img_producto = imagen
                    pro.save()#Actualizamos la ruta de la imagen con la concatenacion del id recien creado
                data = {'tipo_accion': 'crear','correcto': True}

            elif action == 'editar':

                pro = Producto.objects.get(pk=request.POST['id'])
                pro.nombre_producto = request.POST['nombre_producto']
                pro.descripcion_producto = request.POST['descripcion']
                pro.categoria = Categoria.objects.get(pk=request.POST['id_categoria'])

                if request.FILES:
                    if pro.img_producto.url != "/media/img_defecto.jpg":
                        pro.img_producto.delete()

                    imagen = request.FILES.get("imagen") 
                    imagen.name = str(pro.pk)+"_"+imagen.name
                    pro.img_producto = imagen 


                if int(request.POST['id_marca']) > 0:
                    pro.marca = Marca.objects.get(pk=request.POST['id_marca'])

                
                pro.save()
                data = {'tipo_accion': 'editar','correcto': True}

            elif action == 'eliminar':
                pro = Producto.objects.get(pk=request.POST['id'])
                if pro.img_producto.url != "/media/img_defecto.jpg":
                    pro.img_producto.delete()

                pro.delete()
                data = {'tipo_accion': 'eliminar','correcto': True}
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
            data = {'tipo_accion': 'error','correcto': False, 'error': str(e)}

        return JsonResponse(data, safe=False)
    elif request.method == 'GET':
        categorias = Categoria.objects.all()
        marcas = Marca.objects.all()
        return render(request, 'producto/crear_producto.html',{'categorias':categorias,'marcas':marcas})

# clases par vistas
class ProductosListView(ListView):
    template_name = "producto/productos_all.html"
    model = Producto
    ordering = 'nombre_producto'
    paginate_by = 12
    context_object_name = 'productos'
    
    def get_queryset(self):
        prod = Producto.objects.all()
        return (prod)
    
    def get_context_data(self, **kwargs):
        context = super(ProductosListView, self).get_context_data(**kwargs)
        context['cats'] = Categoria.objects.all()
        return context




class ProductDetailView(DetailView):
    model = Producto
    template_name = 'producto/producto_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['producto'] = Producto.objects.get(pk=self.kwargs['pk'])
        return context



class ProductosByCategoriaListView(ListView):
    template_name = "producto/producto_categoria.html"
    context_object_name = 'productos_cat'

    def get_queryset(self):
        cat_prod = self.kwargs['pk']
        lista = Producto.objects.filter(
            categoria__pk=cat_prod
        )
        return (lista)
    def get_context_data(self, **kwargs):
        context = super(ProductosByCategoriaListView, self).get_context_data(**kwargs)
        context['cat_id'] = Categoria.objects.get(pk=self.kwargs['pk'])
        context['cats'] = Categoria.objects.all()
        return context

templates/producto/producto_categoria.html
{% extends "base.html" %}

{% load  static %}

{% block title %}
Distribuidora Venecia
{% endblock title %}

{% block content %}
<section class="py-5" style="background: #273c75">
    <div class="container">
        <h2 class="text-white">Distribuidora Venecia</h2>
        <ol class="breadcrumb ondark mb-0">
            <li class="breadcrumb-item"><a href="/">Inicio</a></li>
            <li class="breadcrumb-item">Todos los productos para la categoria: {{ cat_id.nombre_categoria }}</li>
        </ol>
    </div> <!-- container //  -->
</section>
<!-- ============== SECTION PAGETOP END// ============== -->
<br>
<!-- ============== SECTION CONTENT ============== -->
<section class="padding-y">
    <div class="container">
        <div class="row">
            <aside class="col-lg-2">

                <button class="btn btn-outline-secondary mb-3 w-100  d-lg-none" data-bs-toggle="collapse"
                    data-bs-target="#aside_filter">Mostrar filtros</button>

                <!-- ===== Card for sidebar filter ===== -->
                <div id="aside_filter" class="collapse card d-lg-block mb-5">

                    <article class="filter-group">
                        <header class="card-header">
                            <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside1">
                                <i class="icon-control fa fa-chevron-down"></i> Nuestras categorías
                            </a>
                        </header>
                        <div class="collapse show" id="collapse_aside1">
                            <div class="card-body">
                                <ul class="list-menu">
                                    {% for categoria  in cats %}

                                    {% ifequal categoria.pk id_categoria %}
                                    <li><a href="{% url 'producto_app:producto_categoria' categoria.pk %}">
                                            <span
                                                style="color: #0d6efd;"><u>{{categoria.nombre_categoria}}</u></span></a>
                                    </li>
                                    {% else %}
                                    <li><a href="{% url 'producto_app:producto_categoria' categoria.pk %}">
                                            {{categoria.nombre_categoria}}</a>
                                    </li>
                                    {% endifequal %}

                                    {% endfor %}
                                </ul>
                            </div> <!-- card-body.// -->
                        </div> <!-- collapse.// -->
                    </article> <!-- filter-group // -->
                </div> <!-- card.// -->
                <!-- ===== Card for sidebar filter .// ===== -->

            </aside> <!-- col .// -->
            <main class="col-lg-9 ms-3 me-3">
                <!-- ========= content items ========= -->
                <div class="row">
                    {% for prod in productos_cat %}
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <figure class="card card-product-grid">
                            <div class="img-wrap">
                                <a href="{% url 'producto_app:producto_detail' prod.id %}">
                                    <img src="{{ prod.img_producto.url }}" class="btn img-fluid"
                                        style="width: auto; height: auto;" alt="">
                                </a>
                            </div>
                            <figcaption class="info-wrap border-top">
                                <a href="{% url 'producto_app:producto_detail' prod.id %}"
                                    class="title text-truncate">{{ prod.nombre_producto }}</a>
                                <small class="text-muted">{{ prod.descripcion_producto|truncatewords:5 }}</small>
                            </figcaption>
                        </figure>
                    </div> <!-- col end.// -->
                    {% endfor %}
                </div> <!-- row end.// -->
                <div class="row">
                    {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Atras">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}
                            {% for page in page_obj.paginator.page_range %}

                            {% ifequal page page_obj.number  %}
                            <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% endifequal %}

                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Siguiente">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </main> <!-- col .// -->
        </div> <!-- row .// -->
    </div>
</section>
{% endblock content %}

templates/producto/producto_detail.html
{% extends "base.html" %}

{% load  static %}

{% block title %}
Distribuidora Venecia
{% endblock title %}

{% block content %}

<!-- ============== SECTION PAGETOP ============== -->

<section class="py-5" style="background: #273c75">
    <div class="container">
        <h2 class="text-white">Distribuidora Venecia</h2>
        <ol class="breadcrumb ondark mb-0">
            <li class="breadcrumb-item"><a href="/">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{% url 'producto_app:producto_all' %}">Producto</a></li>
            <li class="breadcrumb-item">Producto: {{ producto.nombre_producto }}</li>
        </ol>
    </div> <!-- container //  -->
</section>
<!-- ============== SECTION PAGETOP END// ============== -->
<br>
<!-- ============== SECTION CONTENT ============== -->
<section class="bg-light padding-y-sm">

    <!-- ============== SECTION CONTENT ============== -->
    <section class="padding-y">
        <div class="container">

            <div class="row">
                <aside class="col-lg-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap img-thumbnail">
                            <a data-fslightbox="mygalley" data-type="image" href="{{ productoids.img_producto.url }}">
                                <img height="560" src="{{ producto.img_producto.url }}" class="img-fluid"
                                    style="width: auto; height: 560px;" alt="">
                            </a>
                            <!-- </div> img-big-wrap.//
        <div class="thumbs-wrap">
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big1.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb1.jpg"> 
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big2.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb2.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big3.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb3.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big4.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb4.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb.jpg">  
          </a>
        </div> thumbs-wrap.// -->
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-lg-6">
                    <article class="ps-lg-3">
                        <h4 class="title text-dark">{{ producto.nombre_producto }} </h4>
                        <!-- <div class="mb-3"> 
          <var class="price h5">Lps. {{ productoids.precio }}</var> 
          <span class="text-muted">/Unidad</span> 
        </div>  -->
                        <!-- {{ producto. }} -->

                        <dl class="row padding-y">
                            <dt class="col-3">Marca:</dt>
                            <dd class="col-9">{{ producto.marca.nombre_marca }}</dd>

                            <dt class="col-3">Modelo:</dt>
                            <dd class="col-9">{{ producto.modelo }}</dd>

                            <dt class="col-3">Categoria:</dt>
                            <dd class="col-9">{{ producto.categoria.nombre_categoria }}</dd>

                            <dt class="col-3">Descripción:</dt>
                            <dd class="col-9">{{ producto.descripcion_producto }}</dd>

                        </dl>
                    </article> <!-- product-info-aside .// -->
                </main> <!-- col.// -->
            </div> <!-- row.// -->

        </div> <!-- container .//  -->
    </section>
    <!-- ============== SECTION CONTENT END// ============== -->

    <!-- ============== SECTION  ============== -->
    <!-- <section class="padding-y bg-light border-top">
        <div class="container">
            <div class="row">
                <aside class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Similar items</h5>

                            <article class="itemside mb-3">
                                <a href="#" class="aside">
                                    <img src="images/items/8.jpg" width="96" height="96" class="img-md img-thumbnail">
                                </a>
                                <div class="info">
                                    <a href="#" class="title mb-1"> Rucksack Backpack Large <br> Line Mounts </a>
                                    <strong class="price"> $38.90</strong>
                                </div>
                            </article>

                            <article class="itemside mb-3">
                                <a href="#" class="aside">
                                    <img src="images/items/9.jpg" width="96" height="96" class="img-md img-thumbnail">
                                </a>
                                <div class="info">
                                    <a href="#" class="title mb-1"> Summer New Men's Denim <br> Jeans Shorts </a>
                                    <strong class="price"> $29.50</strong>
                                </div>
                            </article>

                            <article class="itemside mb-3">
                                <a href="#" class="aside">
                                    <img src="images/items/10.jpg" width="96" height="96" class="img-md img-thumbnail">
                                </a>
                                <div class="info">
                                    <a href="#" class="title mb-1"> T-shirts with multiple colors, for men and lady </a>
                                    <strong class="price"> $120.00</strong>
                                </div>
                            </article>

                            <article class="itemside mb-3">
                                <a href="#" class="aside">
                                    <img src="images/items/11.jpg" width="96" height="96" class="img-md img-thumbnail">
                                </a>
                                <div class="info">
                                    <a href="#" class="title mb-1"> Blazer Suit Dress Jacket for Men, Blue color </a>
                                    <strong class="price"> $339.90</strong>
                                </div>
                            </article>

                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </section> -->
    <!-- =============== SECTION  END// ============== -->

    {% endblock content %}

templates/producto/producto_last.html
{% load  static %}

<section class="padding-top">
    <div class="container">

        <header class="section-heading">
            <h3 class="section-title">Nuevos Productos</h3>
        </header>

        <div class="row">
            {% for prod in last_productos %}
            <div class="col-lg-3 col-md-6 col-sm-6">
                <figure class="card card-product-grid">
                    <a href="{% url 'producto_app:producto_detail' prod.id %}" class="img-wrap">
                        <img src="{{ prod.img_producto.url }}">
                    </a>
                    <figcaption class="info-wrap border-top">
                        <a href="#" class="float-end btn btn-light btn-icon"> <i class="fa fa-eye-open"></i> </a>
                        <a href="{% url 'producto_app:producto_detail' prod.id %}" class="title text-truncate">{{ prod.nombre_producto }}</a>
                        <small class="text-muted">{{ prod.descripcion_producto|truncatechars:20 }}</small>
                    </figcaption>
                </figure>
            </div> <!-- col end.// -->
            {% endfor %}
        </div> <!-- row end.// -->

    </div> <!-- container end.// -->
</section>

templates/producto/productos_all.html
{% extends "base.html" %}

{% load  static %}

{% block title %}
Distribuidora Venecia
{% endblock title %}

{% block content %}
<section class="py-5" style="background: #273c75">
    <div class="container">
        <h2 class="text-white">Distribuidora Venecia</h2>
        <ol class="breadcrumb ondark mb-0">
            <li class="breadcrumb-item"><a href="/">Inicio</a></li>
            <li class="breadcrumb-item">Todos los productos</li>
        </ol>
    </div> <!-- container //  -->
</section>
<!-- ============== SECTION PAGETOP END// ============== -->
<br>

<!-- ============== SECTION CONTENT ============== -->
<section class="padding-y">
    <div class="container">
        <div class="row">
            <aside class="col-lg-3">

                <button class="btn btn-outline-secondary mb-3 w-100  d-lg-none" data-bs-toggle="collapse"
                    data-bs-target="#aside_filter">Mostrar filtros</button>

                <!-- ===== Card for sidebar filter ===== -->
                <div id="aside_filter" class="collapse card d-lg-block mb-5">

                    <article class="filter-group">
                        <header class="card-header">
                            <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside1">
                                <i class="icon-control fa fa-chevron-down"></i> Nuestras categorías
                            </a>
                        </header>
                        <div class="collapse show" id="collapse_aside1">
                            <div class="card-body">
                                <ul class="list-menu">
                                    {% for categoria  in cats %}

                                    {% ifequal categoria.pk id_categoria %}
                                    <li><a href="{% url 'producto_app:producto_categoria' categoria.pk %}">
                                            <span
                                                style="color: #0d6efd;"><u>{{categoria.nombre_categoria}}</u></span></a>
                                    </li>
                                    {% else %}
                                    <li><a href="{% url 'producto_app:producto_categoria' categoria.pk %}">
                                            {{categoria.nombre_categoria}}</a>
                                    </li>
                                    {% endifequal %}

                                    {% endfor %}
                                </ul>
                            </div> <!-- card-body.// -->
                        </div> <!-- collapse.// -->
                    </article> <!-- filter-group // -->
                </div> <!-- card.// -->
                <!-- ===== Card for sidebar filter .// ===== -->

            </aside> <!-- col .// -->
            <main class="col-lg-9">
                <!-- ========= content items ========= -->
                <div class="row">
                    {% for prod in productos %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <figure class="card card-product-grid">
                            <div class="img-wrap">
                                <a href="{% url 'producto_app:producto_detail' prod.id %}">
                                    <img src="{{ prod.img_producto.url }}" class="btn img-fluid"
                                        style="width: auto; height: 250px;" alt="">
                                </a>
                            </div>
                            <figcaption class="info-wrap border-top">
                                <a href="{% url 'producto_app:producto_detail' prod.id %}"
                                    class="title text-truncate">{{ prod.nombre_producto }}</a>
                                <small class="text-muted">{{ prod.descripcion_producto|truncatewords:5 }}</small>
                            </figcaption>
                        </figure>
                    </div> <!-- col end.// -->
                    {% endfor %}
                </div> <!-- row end.// -->
                <div class="row">
                    {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Atras">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}
                            {% for page in page_obj.paginator.page_range %}

                            {% ifequal page page_obj.number  %}
                            <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% endifequal %}

                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Siguiente">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </main> <!-- col .// -->
        </div> <!-- row .// -->
    </div>
</section>
{% endblock content %}