apps/busqueda/urls.py
from django.urls import path
from . import views
from apps.busqueda.views import *

app_name = "busqueda_app"


urlpatterns = [
     path("productosq", busqueda_producto, name="busqueda_producto"),
     path('productos/<int:id_categoria>/',busqueda_categoria, name='busqueda_categoria'),
]

apps/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('', 
        views.IndexHomeView.as_view(), 
    name='index',
    ),
    path('administracion', 
        views.DashboardIndexView.as_view(), 
    name='dashboard_index',
    ),
    path('ubicacion',views.UbicacionView.as_view(),name='mapa'),
]

apps/producto/urls.py
from django.urls import path
from . import views
from apps.producto.views import *

app_name = "producto_app"


urlpatterns = [
     path("producto/ajax", producto_ajax, name="producto_ajax"),
     path("producto/<pk>", views.ProductDetailView.as_view(), name='producto_detail'),
     path('productos', views.ProductosListView.as_view(), name='producto_all'),
     path('productos-categoria/<int:pk>', views.ProductosByCategoriaListView.as_view(), name='producto_categoria'),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', 
        admin.site.urls
    ),
    path('', 
        include(('apps.home.urls'), namespace='home'),
    ),
    path('', 
        include(('apps.categoria.urls'), namespace='categoria'),
    ),
    #path('', include('apps.carrusel.urls')),
    path('', include(('apps.producto.urls'), namespace='producto')),
    path('', include(('apps.marca.urls'), namespace='marca')),
    path('', include(('apps.login.urls'), namespace='login')),
    path('', include(('apps.busqueda.urls'), namespace='busqueda')),
    path('', include(('apps.carrusel.urls'), namespace='carrusel')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}

<footer class="section-footer  footer-dark" style="background: #fbc531">
    <div class="container">
        <section class="footer-main padding-y">
            <div class="row">
                <aside class="col-12 col-sm-12 col-lg-3">
                    <article class="me-lg-6">
                        <a href="#"><img src="{% static 'images/logoBlanco-icon.ico' %}" class="text-white"></a>
                        <p class="mt-3"> © 2022 - 2022 Copyright. <br> Todos los derechos reservados WEDIMS. </p>
                    </article>
                </aside>

                <aside class="col-6 col-sm-4 col-lg-2">
                    <h6 class="title text-white">Acerca de</h6>
                    <ul class="list-menu">
                        <li> <a class="text-white" href="#">Sobre Nosotros</a></li>
                        <li> <a class="text-white" href="{% url 'home_app:mapa' %}">Ubicacion</a></li>
                    </ul>
                </aside>

                <aside class="col-6 col-sm-4 col-lg-2">
                    <h6 class="title text-white">Contáctanos</h6>
                    <ul class="list-menu">
                        <li class="mb-2">
                        <li><a href="tel:+504 2780-2002" target="_blank" style="color: white;"> <i
                                    class="icon fa fa-phone text-white"></i> +504 2780-2002 </a></li>
                        </li>
                        <li class="mb-2">
                            <i class="icon fa fa-envelope text-white" style="color: white;"></i> <a
                                href="mailto:cesarzepeda98@yahoo.com">cesarzepeda98@yahoo.com</a>
                        </li>
                        <li><a href="https://www.facebook.com/Distribuidora-Venecia-130431524223334" target="_blank"
                                style="color: white;" class="text-white"> <i class="icon fab fa-facebook "></i> Facebook </a></li>
                        <li><a href="https://www.facebook.com/Distribuidora-Venecia-130431524223334"
                                style="color: white;" class="text-white" target="_blank"> <i class="icon fab fa-instagram"></i> Instagram
                            </a></li>
                    </ul>
                </aside>
            </div> <!-- row.// -->
        </section> <!-- footer-top.// -->
    </div> <!-- container end.// -->
    <script>
        $(document).ready(function () {

            $('.ir-arriba').click(function () {
                $('body, html').animate({
                    scrollTop: '0px'
                }, 300);
            });

            $(window).scroll(function () {
                if ($(this).scrollTop() > 0) {
                    $('.ir-arriba').slideDown(300);
                } else {
                    $('.ir-arriba').slideUp(300);
                }
            });

        });
    </script>

</footer>

templates/includes/header.html
{% load  static %}

<header class="section-header">

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row gy-3 align-items-center">
                <div class="col-lg-2 col-md-3 col-4">
                    <a href="/" class="brand-wrap">
                        <img class="rounded" height="75" src="{% static '/images/logo-white.ico' %}">
                    </a> <!-- brand-wrap end.// -->
                </div>
                <div class="order-md-last col-lg-5 col-md-5 col-8">
                    <div class="float-end">
                        <!-- Large button groups (default and split) -->
                        <div class="btn-group">
                            <button class="btn btn-lg dropdown-toggle btn-light" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <svg xmlns="{% static 'images/icons/carrusel/whatsapp.svg' %}" width="30" height="30"
                                    fill="currentColor" class="bi bi-whatsapp" style="color: rgb(7, 94, 84);"
                                    viewBox="0 0 16 16">
                                    <path
                                        d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item"
                                        href="https://api.whatsapp.com/send?phone=+504 9331-1282&text=nuestromensaje"
                                        target="_blank">
                                        <svg xmlns="{% static 'images/icons/carrusel/whatsapp.svg' %}" width="20"
                                            height="20" fill="currentColor" class="bi bi-whatsapp"
                                            style="color: rgb(37, 211, 102);" viewBox="0 0 16 16">
                                            <path
                                                d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                                        </svg>
                                        <span class="text-primary d-none d-lg-inline-block">+504 9331-1282</span>
                                    </a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item"
                                        href="https://api.whatsapp.com/send?phone=+504 3382-8021&text=nuestromensaje"
                                        target="_blank">
                                        <svg xmlns="{% static 'images/icons/carrusel/whatsapp.svg' %}" width="20"
                                            height="20" fill="currentColor" class="bi bi-whatsapp"
                                            style="color: rgb(37, 211, 102);" viewBox="0 0 16 16">
                                            <path
                                                d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                                        </svg>
                                        <span class="text-primary d-none d-lg-inline-block">+504 3382-8021</span>
                                    </a></li>
                            </ul>
                        </div>

                    </div>
                </div> <!-- col end.// -->
                <div class="col-lg-5 col-md-4 col-12">
                    <form action="{% url 'busqueda_app:busqueda_producto' %}" method="GET">
                        <div class="input-group w-100">
                            <input type="text" name="busqueda" class="form-control" placeholder="¿Qué está buscando?"
                                value="{{ request.GET.busqueda }}" id="busqueda" style="width:55%;">

                            <button class="btn btn-light">
                                <i class="fa fa-search"></i>
                            </button>
                        </div> <!-- input-group end.// -->
                    </form> <!-- search-wrap end.// -->
                </div> <!-- col end.// -->
            </div> <!-- row end.// -->
        </div> <!-- container end.// -->
    </section> <!-- header-main end.// -->


    <nav class="navbar navbar-dark navbar-expand-lg border-bottom" style="background: #fbc531">
        <div class="container ">
            <button class="navbar-toggler border" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_main"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbar_main">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link ps-0 text-white" href="#" data-bs-toggle="dropdown"> <i class="fa fa-bars text-white"></i>
                            Categorias </a>
                        <ul class="dropdown-menu text-white">
                            {% for cat in ctx_categorias %}
                            <li> <a class="dropdown-item btn tbn-sm"
                                    href="{% url 'producto_app:producto_categoria' cat.pk %}" role="button"
                                    aria-disabled="true">{{ cat.nombre_categoria }} </a> </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'producto_app:producto_all' %}">Productos</a>
                    </li>
                </ul>
            </div> <!-- collapse end.// -->
        </div> <!-- container end.// -->
    </nav> <!-- navbar end.// -->
</header> <!-- section-header end.// -->