apps/carrusel/urls.py
from django.urls import path
from . import views
from apps.carrusel.views import *


app_name = 'carrusel_app'

urlpatterns = [
    
    path('gestion_carrusel/ajax', gestion_carrusel_ajax, name='gestion_carrusel_ajax',
    ),
]

apps/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('', 
        views.IndexHomeView.as_view(), 
    name='index',
    ),
    path('administracion', 
        views.DashboardIndexView.as_view(), 
    name='dashboard_index',
    ),
    path('ubicacion',views.UbicacionView.as_view(),name='mapa'),
]

apps/marca/urls.py
from django.urls import path
from . import views
from apps.marca.views import *

app_name = "marca_app"


urlpatterns = [
     path("marca/ajax", marca_ajax, name="marca_ajax"),
]

apps/producto/urls.py
from django.urls import path
from . import views
from apps.producto.views import *

app_name = "producto_app"


urlpatterns = [
     path("producto/ajax", producto_ajax, name="producto_ajax"),
     path("producto/<pk>", views.ProductDetailView.as_view(), name='producto_detail'),
     path('productos', views.ProductosListView.as_view(), name='producto_all'),
     path('productos-categoria/<int:pk>', views.ProductosByCategoriaListView.as_view(), name='producto_categoria'),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', 
        admin.site.urls
    ),
    path('', 
        include(('apps.home.urls'), namespace='home'),
    ),
    path('', 
        include(('apps.categoria.urls'), namespace='categoria'),
    ),
    #path('', include('apps.carrusel.urls')),
    path('', include(('apps.producto.urls'), namespace='producto')),
    path('', include(('apps.marca.urls'), namespace='marca')),
    path('', include(('apps.login.urls'), namespace='login')),
    path('', include(('apps.busqueda.urls'), namespace='busqueda')),
    path('', include(('apps.carrusel.urls'), namespace='carrusel')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/dashboard/dashboard_header.html
{% load static %}
<header class="section-header border-bottom">
    <nav class="navbar navbar-expand-lg navbar-light" style="background: #dcdde1">
      <div class="container">
        <a class="navbar-brand" href="/">
          <img src="{% static '/images/logo-white.ico' %}" height="" class="rounded">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_main" aria-controls="navbar_main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
      <div class="collapse navbar-collapse"  id="navbar_main">
          <ul class="navbar-nav ms-auto me-sm-2 mt-2 mt-lg-0">
            <li class="nav-item  me-2 active">
              <a class="nav-link" href="{% url 'home_app:dashboard_index' %}"> Home 
              </a>
            </li>
            <li class="nav-item me-2">
              <a class="nav-link" href="{% url 'producto:producto_ajax' %}">Porductos</a>
            </li>
            <li class="nav-item me-2">
              <a class="nav-link" href="{% url 'categoria:categoria_ajax' %}">Categorias</a>
            </li>
            <li class="nav-item me-2">
              <a class="nav-link" href="{% url 'marca:marca_ajax' %}">Marcas</a>
            </li>
            <li class="nav-item me-2">
              <a class="nav-link" href="{% url 'carrusel:gestion_carrusel_ajax' %}">Carrusel</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link py-0 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="icon-xs bg-gray rounded-circle me-2"><i class="fa fa-user"></i> </span>
                <span>{{request.user|title}}</span>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li> <a class="dropdown-item" href="#">Perfil</a> </li>
                <li> <a class="dropdown-item" href="#"></a> </li>
                <li> <hr class="dropdown-divider"> </li>
                <li> <a class="dropdown-item" id="cerrar_sesion" href="#">Salir</a> </li>
              </ul>
            </li>
          </ul>
        </div>

      </div>
    </nav> <!-- navbar end.// -->
  </header> <!-- section-header end.// -->
  