apps/carrusel/urls.py
from django.urls import path
from . import views
from apps.carrusel.views import *


app_name = 'carrusel_app'

urlpatterns = [
    
    path('gestion_carrusel/ajax', gestion_carrusel_ajax, name='gestion_carrusel_ajax',
    ),
]

apps/login/urls.py
from django.urls import path
from . import views
from apps.login.views import *

app_name = "login_app"


urlpatterns = [
     path("login", login, name="login"),
     path("cerrar_sesion", cerrar_sesion, name="cerrar_sesion"),
]

apps/marca/urls.py
from django.urls import path
from . import views
from apps.marca.views import *

app_name = "marca_app"


urlpatterns = [
     path("marca/ajax", marca_ajax, name="marca_ajax"),
]

apps/producto/urls.py
from django.urls import path
from . import views
from apps.producto.views import *

app_name = "producto_app"


urlpatterns = [
     path("producto/ajax", producto_ajax, name="producto_ajax"),
     path("producto/<pk>", views.ProductDetailView.as_view(), name='producto_detail'),
     path('productos', views.ProductosListView.as_view(), name='producto_all'),
     path('productos-categoria/<int:pk>', views.ProductosByCategoriaListView.as_view(), name='producto_categoria'),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', 
        admin.site.urls
    ),
    path('', 
        include(('apps.home.urls'), namespace='home'),
    ),
    path('', 
        include(('apps.categoria.urls'), namespace='categoria'),
    ),
    #path('', include('apps.carrusel.urls')),
    path('', include(('apps.producto.urls'), namespace='producto')),
    path('', include(('apps.marca.urls'), namespace='marca')),
    path('', include(('apps.login.urls'), namespace='login')),
    path('', include(('apps.busqueda.urls'), namespace='busqueda')),
    path('', include(('apps.carrusel.urls'), namespace='carrusel')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/dashboard/dashboard_base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Type some info">
    <meta name="author" content="Type name">

    <title>{% block title %} {% endblock title %}</title>

    <!-- Bootstrap css -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- Custom css -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">
    <!--faviicon-->
    <link rel="icon" type="image/png" href="{% static 'images/favicon.ico' %}" sizes="96x96">
    <!-- Para admin Cdns -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.8/sweetalert2.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.css" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

</head>

<body class="bg-light">

    <!-- ================ HEADER ================ -->
    {% include 'includes/dashboard/dashboard_header.html' %}
    <!-- ================ HEADER END.// ================ -->

    {% block content %}

    {% endblock content %}

    <!-- ================ FOOTER ================ -->
    {% include 'includes/dashboard/dashboard_footer.html' %}
    <!-- ================ FOOTER END.// ================ -->

    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom js -->
    <script src="{% static 'js/script.js' %}"></script>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.8/sweetalert2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>

    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.js"></script>

</body>
<script>
    $("#cerrar_sesion").on('click', function(){
        Swal.fire({
            title: '¿Desea cerrar la sesión?',
            icon: 'info',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí',
            cancelButtonText: 'No'
            }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = "{% url 'login_app:cerrar_sesion' %}";

            }
        })
    });
</script>
</html>

templates/dashboard/dashboard_index.html
{% extends "dashboard/dashboard_base.html" %}

{% load  static %}

{% block title %}
Administracion
{% endblock title %}

{% block content %}

<div class="container mt-5">
    <div class="row row-cols-2">
        <div class="col-6 no-gutters">
            <div class="row no-gutters">
                <div class="col text-center">
                    <h4>Gesiton de Productos</h4>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col text-center" >
                    <a href="{% url 'producto:producto_ajax' %}">
                        <img src="{% static 'images\dashboard\productos.png' %}" class="btn img-fluid" style="width: auto; height: 150px;" alt="">
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 no-gutters">
            <div class="row no-gutters">
                <div class="col text-center">
                    <h4>Gesiton de Categorias</h4>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col text-center" >
                    <a href="{% url 'categoria:categoria_ajax' %}">
                        <img src="{% static 'images\dashboard\categoria.png' %}" class="btn img-fluid" style="width: auto; height: 150px;" alt="">
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 no-gutters">
            <div class="row no-gutters">
                <div class="col text-center">
                    <h4>Gesiton de Marcas</h4>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col text-center" >
                    <a href="{% url 'marca:marca_ajax' %}">
                        <img src="{% static 'images\dashboard\marca.png' %}" class="btn img-fluid" style="width: auto; height: 150px;" alt="">
                    </a>
                </div>
            </div>
        </div>
        <div class="col-6 no-gutters">
            <div class="row no-gutters">
                <div class="col text-center">
                    <h4>Gesiton de Carrusel</h4>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col text-center" >
                    <a href="{% url 'carrusel:gestion_carrusel_ajax' %}">
                        <img src="{% static 'images\dashboard\carrusel.png' %}" class="btn img-fluid" style="width: auto; height: 150px;" alt="">
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}